### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by sjmulder** [sjmulder/nbt-js#5]
NBT.js  currently does not work in the browser. I think it’s easiest to use a pre-existing Buffer module, if there is one. The test suite should then also be made to run in the browser.

**Comment by deathcap** [comment]
Maybe could use https://ci.testling.com for browser tests (free for open source, lots of other browser-related npm modules use it)

**Comment by sjmulder** [comment]
I’ve implemented support directly in the source now (without need for pre or postprocessing with any tool).

Citing [my comment from the other ticket](https://github.com/sjmulder/nbt-js/issues/22#issuecomment-263353320):

> Note that
> 
>  * This is largely untested
>  * You need to pass in data as ArrayBuffer objects
>  * Writer’s buffer is made private now. Instead, use its getData() to get an ArrayBuffer.
>  * writeUncompressed also gives you an ArrayBuffer instead of a Buffer now
>  * Compression only works if window.zlib is a zlib module

**Comment by gDKdev** [comment]
Thank you for making a browser only version. I just got this error:

> Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getInt8 (native)
    at nbt.Reader.read (https://gdkdev.github.io/web-scm/lib/nbt-sj.js:370:40)
    at Object.nbt.parseUncompressed (https://gdkdev.github.io/web-scm/lib/nbt-sj.js:538:21)
    at Object.nbt.parse (https://gdkdev.github.io/web-scm/lib/nbt-sj.js:580:24)
    at HTMLElement.<anonymous> (https://gdkdev.github.io/web-scm/test/gistToNBT2.html?f7ab983da36b827389ff71c56e0b3ff3:19:12)
    at HTMLElement.<anonymous> (https://gdkdev.github.io/web-scm/lib/jquery-3.1.1.js:9842:14)
    at Function.each (https://gdkdev.github.io/web-scm/lib/jquery-3.1.1.js:368:19)
    at jQuery.fn.init.each (https://gdkdev.github.io/web-scm/lib/jquery-3.1.1.js:157:17)
    at Object.<anonymous> (https://gdkdev.github.io/web-scm/lib/jquery-3.1.1.js:9841:9)
    at fire (https://gdkdev.github.io/web-scm/lib/jquery-3.1.1.js:3305:31)

**Comment by sjmulder** [comment]
Do you have the NBT file for me to reproduce? You can email it to me privately if you don’t want to share online. (Email address is in my profile.)

**Comment by gDKdev** [comment]
This is the NBT-Data: [data.bin.txt](https://github.com/sjmulder/nbt-js/files/617368/data.bin.txt).
It's from a mod called SuperCircuitMaker, to share the circuits it creates a base64 encoded gist[ (original source](https://gist.github.com/f7ab983da36b827389ff71c56e0b3ff3)).
The data above is already decoded and tested with the other web-app i referred in another issue.

**Comment by gDKdev** [comment]
Seems like the parser doesn't detect compounds correctly. Because the data starts with a compound and the dataType is set to Int8. Also I couldn't force it to use a compound.

**Comment by sjmulder** [comment]
Thanks for your file and testing!

Here's what I found:

 * The file you linked is gzipped, which is fine but…
 * …the initial `hasGzipHeader()` check failed because it couldn't deal with ArrayBuffers. It would return false and the library would incorrectly assume the file is uncompressed and proceed to try and parse it. This is why it couldn't see the compound at the start.

Addressed in https://github.com/sjmulder/nbt-js/commit/7a5c23c8e2f41f3b3b927568caa7151d794f407c, along with a related issue (see notes).

What wil likely happen now when you try to run your code is that it will throw `NBT archive is compressed because zlib is not available`. You have two options: either find a zlib library that exposes a `gunzip()` function that takes a Buffer or Uint8Array, or make sure the files you're getting aren't compressed.

Hope this helps. If you have any ideas please let me know.

**Comment by gDKdev** [comment]
I updated the library, but I still get the same error as you can see [here](https://gdkdev.github.io/web-scm/test/gistToNBT2.html?f7ab983da36b827389ff71c56e0b3ff3).
I noted that you have a parseUncompressed-function. Why not add a parseCompressed-function, so the normal parse-function will try to auto-detect and the other ones force a specific data handling.

**Comment by sjmulder** [comment]
The library should handle this condition a bit more gracefully, but you’re passing in a string instead of an ArrayBuffer. Per the docs:

> ```@param {ArrayBuffer|Buffer} data - gzipped or uncompressed data```

I’ve added task #29 to support arrays and strings because that would be useful especially in the browser, despite strings being a bad fit for binary data. In the meantime you can use a conversion routine like this:

```javascript
function stringToArrayBuffer(str) {
	if (typeof str !== 'string') throw 'str must be a string';
	var i, x, arr = new Uint8Array(str.length);
	for (i = 0; i < str.length; i++) {
		x = str.charCodeAt(i);
		if (x < 0 || x > 255) throw 'Element ' + i + ' out of range: ' + x;
		arr[i] = x;
	}
	return arr.buffer;
}
```

You’re also not checking the `error` argument. As mentioned before you’ll get an error if you pass in gzipped data without a zlib library in `window.zlib`.

**Comment by gDKdev** [comment]
I thought that the atob-function returns a ByteArray.
I found out that neither IE or Chrome Mobile support zlib, later I will try it with my normal setup

I'm not dealing with errors, because I couldn't even get a basic setup to work.

**Comment by sjmulder** [comment]
Closing this because the issues you encountered now have separate tasks. If there’s anything else, feel free to open another ticket.
